reload "KWS.core.options"
reload "KWS.core.plugins"
reload "KWS.core.keymaps"
reload "KWS.lsp.init"
reload "KWS.colourschmes.nordic"

reload "KWS.plugins.lualine"
reload "KWS.plugins.nvim-tree"
reload "KWS.plugins.vimtex"
reload "KWS.plugins.colourizer"
